Design/main 대쉬보드, 프로필 편집 모달 창 구현
NU-WA-Project/FE pull request #58
Opened 2024-02-28 10:02 UTC by suj2n

## Motivation🤔 
(코드 작성 내용, 의도를 설명해주세요)
대쉬보드 UI 구현, 프로필 편집 모달창 UI 구현했습니다 
프로필 편집 모달창은 수정사항 있어 수정할 예정입니다 

## Key Changes 🔑 
(주요 변화를 기입해주세요. 디렉토리 구조/ ui변경 이미지 첨부 등)

![Uploading 스크린샷 2024-02-28 오후 6.27.57.png…]()

대쉬보드안 내용들은 API 나오면 반영해서 수정 필요합니다 

## To Reviewrs 🙏 
(그 외 리뷰어에게 전달 하고 싶은 말을 적어주세요.)
오류사항 있으면 말씀해주세요

2024-02-28 11:05 UTC, jun42 requested changes
- 자잘한 오류가 있어서 수정하고 머지 진행해야 할 것 같습니다. 
- gpt 리뷰에 오타들도 한 번 확인해주시면 감사하겠습니다.

2024-02-28 11:05 UTC, jun42 commented on src/components/Modal/ProfileEdit/ModalBody.jsx
> +export default ModalBody;
![image](https://github.com/NU-WA-Project/FE/assets/118579021/48a2ceee-b458-4fe1-bbed-25e8dbeda33a)
![image](https://github.com/NU-WA-Project/FE/assets/118579021/bb3f3a50-e9a5-411a-8169-fa67b693eda7)
![image](https://github.com/NU-WA-Project/FE/assets/118579021/411188cf-88ae-4cef-82b2-bc125eea032a)


- isOpen 변수 관련 오류와 form이 중첩된 오류가 있습니다. 수정부탁드립니다.

2024-03-01 04:27 UTC, seon-mikim approved these changes
수고하셨습니다.

2024-03-02 08:46 UTC, kimhyoungseok approved these changes
프로필 편집 이미지 옆 작은 동그라미 부분에 원래 숫자가 들어가 있어야 하는 것 같은데 없는 것 같아요!

2024-03-02 08:50 UTC, kimhyoungseok commented
추가로 하단 즐겨찾는 팀원 부분에서 왼쪽 화살표와 오른쪽 화살표- 피그마에 있는 아이콘 사용하시는게 더 이쁠 것 같습니다. 
즐겨찾기에 저장된 팀원 하단에 전화, 메세지, 삭제 버튼 space-between 한번 걸어보시면 각 gap 사이즈 조금 더 늘어날 것 같은데 확인 해보시는게 좋을 것 같아요!

2024-03-04 08:26 UTC, closed without merging